blank_issues_enabled: false

contact_links:
  - name: ğŸ’¡ Feature Request (for Customers / Users)
    url: https://github.com/coldrockgames/.github/issues/new?template=feature.yml
    about: Are missing something in raptor? Let us know!
  - name: ğŸ› ï¸ Create Internal Ticket (for coldrock members)
    url: https://github.com/coldrockgames/.github/issues/new/choose
    about: Part of our team? Choose this!
    
issue_templates:
  - name: "ğŸ Bug Report"
    description: "Something is broken or behaves unexpectedly."
    file: bug_report.yml

  - name: "ğŸ“˜ Story"
    description: "Describe a developer-facing user story or task."
    file: story.yml

  - name: "âœ’ Lore"
    description: "Write a beautiful new piece of game lore."
    file: lore.yml

  - name: "ğŸ¢ Company Task"
    description: "General company-level task, goal or reminder."
    file: company_task.yml