blank_issues_enabled: false

contact_links:
  - name: ğŸ’¡ Feature Request (for Customers / Users)
    url: https://github.com/coldrockgames/.github/issues/new?template=feature.yml
    about: Are missing something in raptor? Let us know!
  - name: ğŸ› ï¸ Create Internal Ticket (for coldrock members)
    url: https://github.com/coldrockgames/.github/issues/new/choose
    about: Part of our team? Choose this!
    
